[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.offset]
x = 0
y = 0

# [terminal.shell]
# program = "/opt/homebrew/bin/zsh"
# args = [
#     "-l",
#     "-c",
#     "cd ~/ && (~/.local/tmux/bin/tmux a -t 0 || ~/.local/tmux/bin/tmux -u)",
# ]

[window]
opacity = 0.4

[colors.normal]
black = "#181818"
red = "#fc4a4f"
green = "#00cf40"
yellow = "#cdcd38"
blue = "#0a2fc4"
magenta = "#c939c4"
cyan = "#5bcdcb"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#ff414c"
green = "#00ff26"
yellow = "#ffff05"
blue = "#6a76fb"
magenta = "#fd7cfc"
cyan = "#00ffff"
white = "#f8f8f8"

[colors.primary]
background = "#000000"

[colors]
cursor = { text = "#181818", cursor = "#03dcfc" }

[mouse]
hide_when_typing = true
